name: Robot Framework CI

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "main" ]


jobs:
    Run-Test:
      runs-on: ubuntu-20.04
      env:
        SITE_URL: ${{ secrets.SITE_URL }}
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
        JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v1
        - uses: actions/cache@v2
          id: cache
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirement.txt') }}
        - name: Install pip dependencies
          run: |
            pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Test
          run: python -m robot --variable BROWSER:headlesschrome --outputdir results ./Tests

        - name: Publish test results
          uses: actions/upload-artifact@v2
          with:
            name: robot-test-results
            path: results